apiVersion: v1
kind: Deployment
metadata:
  name: my-service
  namespace: my-app-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  spec:
    containers:
      - name: my-api-app
        image: my-first-api
    ports:
      - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ClusterIP-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8000
